# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - payroll-func-con-dev-jpw-001

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Optional: Add step to run tests here

      - name: Prepare package (vendor dependencies for Functions Linux)
        run: |
          python -m pip install --upgrade pip
          # 旧ビルド物を念のため掃除（混在回避）
          rm -rf cryptography cffi .python_packages
          # 実行環境に合う manylinux2014 (glibc 2.17系) の wheel を取得
          pip download -r requirements.txt \
            --platform manylinux2014_x86_64 \
            --implementation cp \
            --python-version 311 \
            --abi cp311 \
            --dest wheelhouse
          # ダウンロード済み wheel だけでオフライン同梱
          pip install --no-index --find-links=wheelhouse -r requirements.txt -t .
          # デプロイZIP作成（wheelhouseは除外）
          zip -r release.zip . -x "venv/*" ".git/*" ".github/*" "wheelhouse/*" ".github/**"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # 展開しない。中身チェックは一覧のみ
      - name: Sanity check (zip content)
        run: unzip -l release.zip

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'payroll-func-con-dev-jpw-001'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F53B3874BF9D42649C2EE5AA309676B0 }}